version: "2"
services:
  api:
    container_name: api
    restart: always
    build: ./
    links: 
      - db
    ports: 
      - "3001:3001"
    volumes: 
      - ./:/app
      - /app/node_modules
    depends_on: 
      - db
  db:
    container_name: db
    image: redis
    ports: 
      - "6379:6379"
    restart: always