version: "2"
services:
  # traefik:
  #   image: traefik
  #   command: --web --docker --docker.domain=app.com --logLevel=DEBUG
  #   ports:
  #     - "80:80"
  #     - "8080:8080"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /dev/null:/traefik.toml
  api:
    container_name: api
    restart: always
    build: ./
    links: 
      - db
    ports: 
      - "3001:3000"
    volumes: 
      - ./:/app
      - /app/node_modules
    depends_on: 
      - db
    # labels:
    #   - "traefik.backend=webserver"
    #   - "traefik.frontend.rule=Host:web.pungy.local"
  db:
    container_name: db
    image: redis
    ports: 
      - "6379:6379"
    restart: always
    # volumes: 
    #   - ./data:/data/db